### PR TITLE
Add Easyconfig for Python 3.11.4.

### PR DESCRIPTION
**Pull request by bartoldeman**

### CODE REVIEW

**Comment by mboisson** [comment]
I would say that the "bare" python module should include: 
```pip freeze --all
distlib
filelock
pip
platformdirs
setuptools
virtualenv
wheel
``` 

Those are what get installed if I create a virtual environment and I install --upgrade `pip setuptools virtualenv wheel`  (so, it is these 4 packages + their dependencies)

**Comment by bartoldeman** [comment]
I think they are all in there, or did I miss something?

**Comment by bartoldeman** [comment]
ah, `flit_core` is not in your list, but `flit_core` is a dependency, or else the build breaks... Need to figure out why?

**Comment by mboisson** [comment]
Oh, it might be a build dependency when you're building `setuptools`, `virtualenv`, `wheel` or `pip` from source, but not an actual runtime dependency (?)

**Comment by bartoldeman** [comment]
here's the output installing `wheel` without `flit_core`:

```Processing /tmp/oldeman/avx2/Python/3.11.4/GCCcore-12.3.0/wheel/wheel-0.41.2
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 713, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldeman/.local/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.4/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flit_core'

 (at easybuild/tools/run.py:681 in parse_cmd_output)
```

and `flit_core` is also in our older easyconfig, ie.
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-main/easybuild/easyconfigs/p/Python/Python-3.11.2-GCCcore-11.3.0.eb

**Comment by mboisson** [comment]
now that I think of it, it's quite possible that my virtualenv worked without installing flit_core precisely because it's already in the core module. 

LGTM for merge then

**Pull request merged**
